# Generated by Django 4.2.10 on 2024-04-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamestat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamestat",
            old_name="top_10_achievements",
            new_name="top_5_hours",
        ),
        migrations.RenameField(
            model_name="gamestat",
            old_name="top_10_hours",
            new_name="top_5_last_2weeks",
        ),
    ]
