# Generated by Django 4.2.10 on 2024-04-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamestat",
            "0002_rename_top_10_achievements_gamestat_top_5_hours_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestat",
            name="favorite_game",
        ),
        migrations.AddField(
            model_name="gamestat",
            name="favorite_game_name",
            field=models.CharField(default="favorite_game", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamestat",
            name="favorite_game_playtime",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamestat",
            name="favorite_game_url",
            field=models.URLField(
                default="https://store.steampowered.com/app/730/"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="gamestat",
            name="top_5_hours",
        ),
        migrations.AddField(
            model_name="gamestat",
            name="top_5_hours",
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name="gamestat",
            name="top_5_last_2weeks",
        ),
        migrations.AddField(
            model_name="gamestat",
            name="top_5_last_2weeks",
            field=models.JSONField(default=list),
        ),
    ]
