version: '3.7'
services:
  web:
    build: .
    command: python event_manager/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/team-8-0/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data: