services:
  tgbot:
    build: ./tgbot
    container_name: tgbot
    command: python3 bot.py
    env_file:
      - ./.env.prod
    depends_on:
      - django

  django:
    build: 
      context: ./event_manager
      dockerfile: Dockerfile.prod
    container_name: django
    command: python -m gunicorn event_manager.asgi:application -k uvicorn_worker.UvicornWorker --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - pgdb
      - redis

  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    container_name: pgdb
    ports:
      - 5432:5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    # Чтобы дождаться запуска postgres. TODO: не работает потому что юзера postgres нет
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    build: 
      context: ./event_manager
      dockerfile: Dockerfile.prod
    command: celery -A event_manager worker -l info
    env_file:
      - ./.env.prod
    container_name: celery
    depends_on:
      - redis

  celery-beat:
    build: 
      context: ./event_manager
      dockerfile: Dockerfile.prod
    command: celery -A event_manager beat -l info
    env_file:
      - ./.env.prod
    container_name: celery-beat
    depends_on:
      - redis

  flower:
    container_name: flower
    build: 
      context: ./event_manager
      dockerfile: Dockerfile.prod
    command: celery -A event_manager.celery flower --basic-auth=admin:${PG_PASSWORD}
    env_file:
      - ./.env.prod
    ports:
      - 5555:5555
    depends_on:
      - celery
      - celery-beat

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - django

volumes:
  pgdbdata:
  static_volume:
  media_volume: