# Generated by Django 4.2.10 on 2025-08-25 14:32

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название игры', max_length=500, verbose_name='название')),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
                'ordering': ['name'],
            },
        ),
        TrigramExtension()  # ЭТО Я САМ ДОБАВИЛ
    ]
