# Generated by Django 4.2.10 on 2025-08-25 15:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
