# Generated by Django 4.2.10 on 2024-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/", verbose_name="аватарка"
            ),
        ),
    ]
