# Generated by Django 4.2.10 on 2025-08-26 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid_utils.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0002_game_trgm_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Короткий заголовок. Макс. 150 симв.",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Подробное описание", verbose_name="описание"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "end",
                    models.DateTimeField(
                        help_text="Дата проведения", null=True, verbose_name="дата"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Доступ из профиля",
                        verbose_name="приватное",
                    ),
                ),
                (
                    "is_canceled",
                    models.BooleanField(default=False, verbose_name="отменено"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите кол-во участников, или оставьте пустым",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="максимальное количество участников",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="categories.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="games.game",
                        verbose_name="игра",
                    ),
                ),
            ],
            options={
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
            },
        ),
        migrations.CreateModel(
            name="EventParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Обязательно буду"),
                            (1, "Пока решаю"),
                            (2, "Не пойду"),
                        ],
                        default=1,
                        verbose_name="статус",
                    ),
                ),
                (
                    "present",
                    models.BooleanField(default=True, verbose_name="присутствовал"),
                ),
                (
                    "notified",
                    models.BooleanField(default=False, verbose_name="уведомлен"),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Администратор"),
                            (1, "Организатор"),
                            (2, "Участник"),
                        ],
                        default=2,
                        verbose_name="роль",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="мероприятие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник мероприятия",
                "verbose_name_plural": "участники мероприятия",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="events.EventParticipants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(is_private=False),
                fields=["id"],
                name="public_events_idx",
            ),
        ),
    ]
