# Generated by Django 4.2.10 on 2025-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventparticipants",
            name="role",
        ),
        migrations.AlterField(
            model_name="eventparticipants",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "заявка отправлена"),
                    (1, "приглашение отправлено"),
                    (2, "заявка принята"),
                ],
                default=0,
                verbose_name="статус",
            ),
        ),
    ]
