# Generated by Django 4.2.10 on 2024-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_canceled",
            field=models.BooleanField(default=False, verbose_name="отменено"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="приватное"),
        ),
    ]
