# Generated by Django 4.2.10 on 2025-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventparticipants_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipants',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'заявка отправлена'), (1, 'приглашение отправлено'), (2, 'заявка принята'), (3, 'заявка отозвана')], default=0, verbose_name='статус'),
        ),
    ]
