# Generated by Django 4.2.10 on 2024-04-12 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_eventparticipants_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Больше 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="максимальное количество участников",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Доступ только по ссылке",
                verbose_name="приватное",
            ),
        ),
    ]
