# Generated by Django 4.2.10 on 2025-08-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_trgm_idx'),
        ('events', '0003_alter_eventparticipants_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.ForeignKey(help_text='Если вашей игры нет напишите "Custom" ', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game', verbose_name='игра'),
        ),
    ]
