# Generated by Django 4.2.10 on 2025-09-01 11:11

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(help_text='Дата проведения', null=True, validators=[events.models.future_datetime], verbose_name='дата'),
        ),
    ]
