# Generated by Django 4.2.10 on 2024-04-12 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0004_event_max_participants_alter_event_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="events.EventParticipants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
