# Generated by Django 4.2.10 on 2024-04-13 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите кол-во участников, или оставьте пустым",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="максимальное количество участников",
            ),
        ),
    ]
