# Generated by Django 4.2.10 on 2024-04-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("events", "0009_alter_event_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipants",
            name="notified",
            field=models.BooleanField(default=False, verbose_name="уведомлен"),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="categories.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipants",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_info",
                to="events.event",
                verbose_name="мероприятие",
            ),
        ),
    ]
