# Generated by Django 4.2.10 on 2024-04-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_category"),
        ("events", "0011_alter_eventparticipants_event"),
    ]

    operations = []
