# Generated by Django 4.2.10 on 2024-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_merge_20240419_1949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_private",
            field=models.BooleanField(
                default=False, help_text="Доступ из профиля", verbose_name="приватное"
            ),
        ),
    ]
