# Generated by Django 4.2.10 on 2025-08-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('events', '0013_alter_eventparticipants_options_alter_event_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Подробное описание', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Короткий заголовок. Макс. 150 симв.', max_length=150, verbose_name='название'),
        ),
    ]
