# Generated by Django 4.2.10 on 2025-08-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_category_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_private'], name='events_even_is_priv_d7766c_idx'),
        ),
    ]
