# Generated by Django 4.2.10 on 2025-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_events_even_is_priv_d7766c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_is_priv_d7766c_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q('is_private=false'), fields=['id'], name='public_events_idx'),
        ),
    ]
