# Generated by Django 4.2.10 on 2025-08-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('games', '0001_initial'),
        ('events', '0016_remove_event_events_even_is_priv_d7766c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game', verbose_name='игра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.category', verbose_name='категория'),
        ),
    ]
