# Generated by Django 4.2.10 on 2025-08-26 08:04

from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_game_alter_event_category"),
    ]

    operations = [
    ]
