# Generated by Django 4.2.10 on 2025-08-26 08:04

from django.db import migrations, models
import uuid_utils.compat


def gen_uuid(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for row in Event.objects.all():
        row.uuid = uuid_utils.compat.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_auto_20250826_1104"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
