# Generated by Django 4.2.10 on 2025-08-26 08:15

from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_auto_20250826_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(default=uuid_utils.compat.uuid4, unique=True),
        ),
    ]
