# Generated by Django 4.2.10 on 2025-08-26 08:19

from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_auto_20250826_1115"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="id",
        ),
        migrations.RenameField(
            model_name="event",
            new_name="id",
            old_name="uuid",
        ),
    ]
