# Generated by Django 4.2.10 on 2025-08-26 08:33

from django.db import migrations, models
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_remove_event_uuid_alter_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid_utils.compat.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
