# Generated by Django 4.2.10 on 2025-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_alter_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipants",
            name="event",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to="events.event",
                verbose_name="мероприятие",
            ),
        ),
    ]
